PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?quantityKind ?label
WHERE {
    ?quantityKind a qudt:QuantityKind .
    OPTIONAL {
        ?quantityKind rdfs:label ?label .
        FILTER(LANG(?label) = "" || LANG(?label) = "en")
    }
}
LIMIT $limit
OFFSET $offset
